// <auto-generated />
namespace RestaurantFinder.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Restaurantaddtimeslot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Restaurantaddtimeslot));
        
        string IMigrationMetadata.Id
        {
            get { return "202002222104370_Restaurantaddtimeslot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
